---
plugins:

  taskbot:
    '/taskbot/new': newtask
    '/taskbot/item/(.taskid)': item
    '/taskbot/list': tasks
    '/taskbot/edit/(.taskid)': open
    '/taskbot/ical': ical

  rss:
    '/rss/:mailbox': rss
    '/atom/:mailbox': atom

  notify:
    '/notify': notify
    '/tags': tags

  graphs:
    '/graphs': graphs

  tv:
    '/tv/crew/(.first)/(.last)': 'crew'
    '/tv/program/(.program_id)': 'program'
    '/tv/seen/(.show_id)/(.episode_num)/(.seen)': 'seen'
    '/tv/station/hide/(.station_id)/(.hide)': 'hide'
    '/tv/score/(.show)/(.score)': 'score'
    '/tv/rt/(.program_id)': 'rt'
    '/tv/schedule/crew/(.first)/(.last)': 'schedule_crew'
    '/tv/schedule': 'schedule'
    '/tv/schedule/(.program_id)': 'schedule_program'
    '/tv/ical': 'ical'
    '/tv/oldschedule': 'oldschedule'
