
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

# This test is generated by Dist::Zilla::Plugin::Test::PodSpelling
use strict;
use warnings;
use Test::More;
use Test::Requires {
    'Test::Spelling'  => 0.12,
    'Pod::Wordlist' => 0,
};

set_spell_cmd('aspell list');
add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
Alex
White
lib
App
Wubot
Obj
Roles
Reactor
MessageQueue
Plugin
Cache
Util
Colors
WubotX
WebFetch
SQLiteDelete
Tail
TransformField
Config
Conditions
Status
Dumper
WebFetcher
ImageStrip
User
Check
Pulse
TestCase
Web
SQLite
Template
Icon
Console
CopyField
WebUtil
WebMatches
DeleteField
TimeLength
HTMLStrip
HashLookup
Tables
SetField
Split
LocalMessageStore
CleanText
CaptureData
Logger
GraphsWeb
