
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

# This test is generated by Dist::Zilla::Plugin::Test::PodSpelling
use strict;
use warnings;
use Test::More;
use Test::Requires {
    'Test::Spelling'  => 0.12,
    'Pod::Wordlist' => 0,
};

set_spell_cmd('aspell list');
add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
Alex
White
lib
App
Wubot
Reactor
MessageQueue
MakeDirectory
Plugin
Roles
Cache
CleanFilename
Util
Colors
WebFetch
Tail
PathLastUpdate
Status
Dumper
DiskSpace
User
FileRegexp
Pulse
TestCase
GreaterThan
Web
Obj
False
SafariBookmarks
Console
CopyField
WebMatches
FileTail
HTMLStrip
FirefoxBookmarks
HashLookup
Split
LocalMessageStore
SQLite
Arp
Outlook
GraphsWeb
CPAN
WriteFile
WubotX
SQLiteDelete
TransformField
Config
Conditions
WebFetcher
ImageStrip
Check
Directory
Icon
Template
WebUtil
Ping
DeleteField
TimeLength
SetField
Tables
CleanText
CaptureData
Logger
LessThan
Uptime
