=head1 NAME

App::Wubot::Guide::WebUI - guide for using the wubot web interface

=head1 DESCRIPTION

The web interface is still experimental and is frequently changing!

Recently the web ui has been moved out of wubot core and into the
WubotX project.

The recommended method for using the web ui is to clone the WubotX git
repository and run the web ui from there.

  mkdir ~/wubot
  cd ~/wubot
  git clone git://github.com/wu/WubotX.git
  cd WubotX/webui
  cp conf/webui.yaml ~/wubot/config/
  bin/wubot-webui daemon

This assumes that you have already installed App::Wubot.

If you do not have git installed, you can also download and expand the
tarball from github rather than using the 'git clone' command above.

=head1 SEE ALSO

A number of the WubotX extensions have web interfaces.

  https://github.com/wu/WubotX

The WubotX extensions are still under development, and should
eventually be available as separate CPAN modules.
